import { useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight, BedDouble, CalendarDays, Check, Eye, LayoutGrid, List, Plus, Search, Settings2, Wrench, X } from 'lucide-react';
import { Badge, Button, Card, CardHead, Confirm, DataTable, Empty, Fields, Modal, PageMotion, PageTitle, Tabs } from '../components/ui';
import { PropertyMedia } from '../components/PropertyMedia';
import { available, can, dateOffset, live, money, nights, shortDate, today } from '../lib/domain';
import type { Room, State } from '../lib/domain';
import { canEditProperty, roomStatus, roomStatuses } from '../lib/property';
import { useStore } from '../lib/store';
import { TaskForm } from './Operations';

function performance(s: State, room: Room) {
  const since = dateOffset(-29), until = dateOffset(1);
  const bookings = s.reservations.filter(r => r.roomId === room.id && !['Cancelled', 'No-show'].includes(r.status));
  const used = bookings.reduce((sum, r) => sum + Math.max(0, nights(r.checkIn > since ? r.checkIn : since, r.checkOut < until ? r.checkOut : until)), 0);
  return { nights: used, occupancy: Math.min(100, Math.round(used / 30 * 100)), revenue: bookings.reduce((sum, r) => sum + Math.max(0, nights(r.checkIn, r.checkOut) * r.rate - r.discount), 0), bookings: bookings.length };
}
export function RoomManagement() {
  const { s, actor, act } = useStore();
  const [params, setParams] = useSearchParams();
  const navigate = useNavigate();
  const [query, setQuery] = useState('');
  const [form, setForm] = useState<Room | 'new' | null>(null);
  const [selectedId, setSelectedId] = useState('');
  const [statusRoom, setStatusRoom] = useState<Room | null>(null);
  const [deleteRoom, setDeleteRoom] = useState<Room | null>(null);
  const [toggleRoom, setToggleRoom] = useState<Room | null>(null);
  const [resolveRoom, setResolveRoom] = useState<Room | null>(null);
  const [taskRoom, setTaskRoom] = useState('');
  const [cleaningRequired, setCleaningRequired] = useState(true);
  const [view, setView] = useState('list');
  const [start, setStart] = useState(today()), [end, setEnd] = useState(dateOffset(1));
  const owner = actor!.module === 'Owner', staff = actor!.module === 'Staff';
  const editAllowed = canEditProperty(s, actor!, 'rooms');
  const tabs = ['Overview', 'All rooms', 'Room types', 'Pricing', 'Availability', 'Maintenance', ...(owner ? ['Performance'] : [])];
  const tab = tabs.includes(params.get('tab') ?? '') ? params.get('tab')! : params.has('status') ? 'All rooms' : 'Overview';
  const status = params.get('status') ?? 'All', type = params.get('type') ?? 'All', floor = params.get('floor') ?? 'All', sort = params.get('sort') ?? 'number';
  const setFilter = (key: string, value: string) => { const next = new URLSearchParams(params); value === 'All' ? next.delete(key) : next.set(key, value); setParams(next, { replace: true }); };
  const chooseTab = (value: string) => { setQuery(''); setParams({ tab: value }); };
  const filterStatus = (value: string) => { setQuery(''); setParams({ tab: 'All rooms', ...(value === 'All' ? {} : { status: value }) }); };
  const types = [...new Set(s.rooms.map(r => r.type))].sort();
  const floors = [...new Set(s.rooms.map(r => r.floor))].sort();
  const selected = s.rooms.find(r => r.id === selectedId);
  const validRange = start >= today() && end > start;
  const rows = s.rooms.filter(r => `${r.number} ${r.name ?? ''} ${r.type}`.toLowerCase().includes(query.trim().toLowerCase()) && (status === 'All' || roomStatus(s, r) === status) && (type === 'All' || r.type === type) && (floor === 'All' || r.floor === floor) && (tab !== 'Maintenance' || ['Maintenance', 'Out of Service'].includes(roomStatus(s, r)))).sort((a, b) => sort === 'price' ? a.rate - b.rate : sort === 'price-desc' ? b.rate - a.rate : a.number.localeCompare(b.number, undefined, { numeric: true }));
  const clear = () => { setQuery(''); setParams({ tab }); };
  const counts = roomStatuses.map(label => ({ label, count: s.rooms.filter(r => roomStatus(s, r) === label).length }));
  const columns = [
    { key: 'number', label: 'Room', sort: (r: Room) => r.number, render: (r: Room) => <button className="table-link property-room-link" onClick={() => setSelectedId(r.id)}><strong>{r.number} · {r.name ?? r.type}</strong><small>{r.type} · Floor {r.floor}</small></button> },
    { key: 'capacity', label: 'Sleeps', sort: (r: Room) => r.capacity, render: (r: Room) => <>{r.capacity} guests<small>{r.beds ?? 1} {r.bedType ?? 'King'} bed{(r.beds ?? 1) > 1 ? 's' : ''}</small></> },
    { key: 'rate', label: 'Nightly rate', sort: (r: Room) => r.rate, render: (r: Room) => money(r.rate) },
    { key: 'status', label: 'Status', render: (r: Room) => <><Badge>{roomStatus(s, r)}</Badge>{r.status === 'Inspection' && <small>Awaiting inspection</small>}{r.active === false && <small>Inactive</small>}</> },
    { key: 'actions', label: 'Actions', render: (r: Room) => <div className="property-row-actions"><Button variant="ghost" size="sm" aria-label={`View room ${r.number}`} onClick={() => setSelectedId(r.id)}><Eye size={14} /> View</Button>{editAllowed && <Button variant="outline" size="sm" aria-label={`Edit room ${r.number}`} onClick={() => setForm(r)}>Edit</Button>}{editAllowed && <Button variant="ghost" size="sm" aria-label={`Delete room ${r.number}`} onClick={() => setDeleteRoom(r)}>Delete</Button>}</div> },
  ];
  return <PageMotion>
    <PageTitle eyebrow={owner ? 'PROPERTY INTELLIGENCE' : 'EVERY ROOM. EVERY DETAIL.'} title={owner ? 'Rooms & property insights' : 'Rooms & availability'} description={owner ? 'Monitor occupancy, pricing, room performance, and property readiness.' : 'Manage your rooms from the first reservation to the next warm welcome.'} actions={editAllowed ? <Button onClick={() => setForm('new')}><Plus size={16} />Add room</Button> : undefined} />
    <Card className="property-tabs"><Tabs value={tab} onChange={chooseTab} tabs={tabs.map(value => ({ value, label: value }))} /></Card>
    {tab === 'Overview' ? <>
      <div className="property-summary">{counts.map(({ label, count }) => <button key={label} className="property-metric" onClick={() => filterStatus(label)}><span>{label}<ArrowUpRight size={15} /></span><strong>{count}</strong><small>{label === 'Reserved' ? 'Arriving or reserved today' : label === 'Cleaning' ? 'Includes inspection queue' : 'View matching rooms'}</small></button>)}</div>
      <div className="property-columns"><Card><CardHead title="Room collection" subtitle={`${s.rooms.length} rooms across ${types.length} room types`} /><div className="property-type-list">{types.map(type => { const group = s.rooms.filter(r => r.type === type); return <button key={type} onClick={() => setParams({ tab: 'All rooms', type })}><span className="property-type-icon"><BedDouble size={20} /></span><span><strong>{type}</strong><small>{group.length} rooms · from {money(Math.min(...group.map(r => r.rate)))} / night</small></span><ArrowUpRight size={16} /></button>; })}</div></Card><Card><CardHead title="Room activity" subtitle="Latest room and operational updates" /><div className="property-activity">{s.audit.filter(a => /^(room\.|task\.|reservation\.)/.test(a.action)).slice(0, 5).map(a => <div key={a.id}><span className="live-dot" /><span><strong>{a.action.replaceAll('.', ' · ')}</strong><small>{a.detail} · {a.actor} · {shortDate(a.date)}</small></span></div>)}{!s.audit.some(a => /^(room\.|task\.|reservation\.)/.test(a.action)) && <Empty title="Ready for a new day" description="Room and housekeeping updates will appear here." />}</div></Card></div>
    </> : <>
      <Card className="property-filter-card"><div className="property-filters"><label className="search-input"><Search size={16} /><input aria-label="Search rooms" placeholder="Search room number, name or type…" value={query} onChange={e => setQuery(e.target.value)} />{query && <button aria-label="Clear room search" onClick={() => setQuery('')}><X size={15} /></button>}</label><select aria-label="Room status filter" value={status} onChange={e => setFilter('status', e.target.value)}><option value="All">All statuses</option>{roomStatuses.map(x => <option key={x}>{x}</option>)}</select><select aria-label="Room type filter" value={type} onChange={e => setFilter('type', e.target.value)}><option value="All">All room types</option>{types.map(x => <option key={x}>{x}</option>)}</select><select aria-label="Room floor filter" value={floor} onChange={e => setFilter('floor', e.target.value)}><option value="All">All floors</option>{floors.map(x => <option key={x}>{x}</option>)}</select><select aria-label="Sort rooms" value={sort} onChange={e => setFilter('sort', e.target.value)}><option value="number">Room number</option><option value="price">Price: low to high</option><option value="price-desc">Price: high to low</option></select><Button variant="ghost" size="sm" onClick={clear}>Reset filters</Button></div></Card>
      {tab === 'Room types' ? <div className="property-type-grid">{types.filter(t => rows.some(r => r.type === t)).map(t => { const group = rows.filter(r => r.type === t); return <Card key={t} className="card-padding"><BedDouble size={26} /><h2>{t}</h2><p>{group.length} rooms · up to {Math.max(...group.map(r => r.capacity))} guests</p><strong>{money(Math.min(...group.map(r => r.rate)))} – {money(Math.max(...group.map(r => r.rate)))}</strong><Button variant="outline" onClick={() => setParams({ tab: 'All rooms', type: t })}>View rooms <ArrowUpRight size={15} /></Button></Card>; })}</div>
      : tab === 'Availability' ? <Card><CardHead title="Booking availability" subtitle="Maintenance, inactive rooms, and overlapping stays are excluded." /><div className="property-filters"><label className="field"><span>Arrival date</span><input aria-label="Availability arrival" type="date" min={today()} value={start} onChange={e => setStart(e.target.value)} /></label><label className="field"><span>Departure date</span><input aria-label="Availability departure" type="date" min={dateOffset(1, new Date(start + 'T12:00:00'))} value={end} onChange={e => setEnd(e.target.value)} /></label><span>{validRange ? `${rows.filter(r => available(s, r.id, start, end)).length} available for these dates` : 'Select valid future dates with departure after arrival.'}</span></div><DataTable hideToolbar rows={rows} searchBy={r => r.number} columns={[...columns.slice(0, 3), { key: 'availability', label: 'Selected dates', render: r => <Badge>{validRange && available(s, r.id, start, end) ? 'Available' : 'Unavailable'}</Badge> }, { key: 'booking', label: 'Action', render: r => <Button size="sm" variant="outline" disabled={!validRange || !available(s, r.id, start, end)} onClick={() => !owner && can(s, actor!, 'reservations') ? navigate(`/${actor!.module.toLowerCase()}/reservations?new=1&room=${r.id}&checkIn=${start}&checkOut=${end}`) : setSelectedId(r.id)}>{owner ? 'View room' : 'Reserve room'}</Button> }]} /></Card>
      : tab === 'Performance' ? <Card><CardHead title="Room performance" subtitle="Occupancy: reserved room nights in the last 30 days. Revenue: contracted room charges across all stays, before tax." /><DataTable hideToolbar rows={rows} searchBy={r => r.number} columns={[columns[0], { key: 'occupancy', label: '30-day occupancy', sort: r => performance(s, r).occupancy, render: r => `${performance(s, r).occupancy}%` }, { key: 'bookings', label: 'Reservations', sort: r => performance(s, r).bookings, render: r => performance(s, r).bookings }, { key: 'revenue', label: 'Room revenue', sort: r => performance(s, r).revenue, render: r => money(performance(s, r).revenue) }, columns[4]]} /></Card>
      : <Card><CardHead title={tab === 'Pricing' ? 'Room pricing' : tab === 'Maintenance' ? 'Maintenance & out of service' : 'All rooms'} subtitle={`${rows.length} matching rooms · ${s.rooms.length} in your resort`} action={<div className="property-view-toggle"><Button variant={view === 'list' ? 'soft' : 'ghost'} size="icon" aria-label="List view" aria-pressed={view === 'list'} onClick={() => setView('list')}><List size={17} /></Button><Button variant={view === 'grid' ? 'soft' : 'ghost'} size="icon" aria-label="Grid view" aria-pressed={view === 'grid'} onClick={() => setView('grid')}><LayoutGrid size={17} /></Button></div>} />{view === 'list' ? <DataTable key={`${status}-${type}-${floor}-${query}`} hideToolbar rows={rows} searchBy={r => r.number} columns={columns} /> : <div className="property-room-grid">{rows.map(r => <button key={r.id} className="property-room-tile" onClick={() => setSelectedId(r.id)}><img src={r.images?.[0] || '/images/suite.jpg'} alt={r.name ?? r.type} loading="lazy" /><span className="property-tile-body"><span className="flex-between"><strong>Room {r.number}</strong><Badge>{roomStatus(s, r)}</Badge></span><span>{r.name ?? r.type}</span><small>{r.type} · {r.capacity} guests · Floor {r.floor}</small><b>{money(r.rate)} <small>/ night</small></b></span></button>)}{!rows.length && <Empty title="No matching rooms" action={<Button variant="outline" onClick={clear}>Reset filters</Button>} />}</div>}</Card>}
      {tab === 'Room types' && !rows.length && <Empty title="No matching room types" action={<Button variant="outline" onClick={clear}>Reset filters</Button>} />}
    </>}
    {selected && <Modal open wide title={`Room ${selected.number} · ${selected.name ?? selected.type}`} description={`${selected.type} · Floor ${selected.floor} · ${selected.capacity} guests`} onClose={() => setSelectedId('')}><div className="dialog-body property-details"><div className="property-gallery">{(selected.images?.length ? selected.images : ['/images/suite.jpg']).map((src, i) => <img src={src} key={i} alt={`${selected.name ?? selected.type}, image ${i + 1}`} />)}</div><div className="flex-between"><Badge>{roomStatus(s, selected)}</Badge><strong>{money(selected.rate)} / night</strong></div><p>{selected.description || 'A comfortable stay, with every essential close at hand.'}</p><dl className="detail-grid"><div><dt>Beds</dt><dd>{selected.beds ?? 1} {selected.bedType ?? 'King'}</dd></div><div><dt>Capacity</dt><dd>{selected.capacity} guests</dd></div><div><dt>Activity</dt><dd>{selected.active === false ? 'Inactive' : 'Active'}</dd></div><div><dt>30-day occupancy</dt><dd>{performance(s, selected).occupancy}%</dd></div></dl><h3>Room amenities</h3><div className="property-badges">{s.amenities.filter(a => selected.amenityIds?.includes(a.id)).map(a => <Badge key={a.id}>{a.name}{!a.active || a.maintenance ? ' · unavailable' : ''}</Badge>)}{!selected.amenityIds?.length && <span className="muted">No room amenities assigned yet.</span>}</div>{s.reservations.some(r => r.roomId === selected.id && live(r)) && <div className="info-box">{s.reservations.filter(r => r.roomId === selected.id && live(r)).length} live reservation(s) use this room. Reservation dates and contracted rates remain attached to each stay.</div>}<div className="property-detail-actions">{editAllowed && <Button variant="destructive" onClick={() => { setSelectedId(''); setDeleteRoom(selected); }}>Delete room</Button>}{editAllowed && <Button onClick={() => { setSelectedId(''); setForm(selected); }}>Edit room</Button>}{!staff && <><Button variant="outline" onClick={() => { setSelectedId(''); setStatusRoom(selected); }}><Settings2 size={15} />Change status</Button><Button variant="outline" onClick={() => { setSelectedId(''); setToggleRoom(selected); }}>{selected.active === false ? 'Activate room' : 'Deactivate room'}</Button>{['Maintenance', 'Out of Service'].includes(selected.status) && <Button onClick={() => { setSelectedId(''); setCleaningRequired(true); setResolveRoom(selected); }}><Check size={15} />Resolve issue</Button>}</>}{can(s, actor!, 'tasks') && <Button variant="outline" onClick={() => { setSelectedId(''); setTaskRoom(selected.id); }}><Wrench size={15} />Create operational task</Button>}</div></div><div className="dialog-footer"><Button variant="outline" onClick={() => setSelectedId('')}>Close</Button></div></Modal>}
    {form && <RoomForm room={form === 'new' ? undefined : form} onClose={() => setForm(null)} />}
    {deleteRoom && <Confirm title="Are you sure you want to delete this room?" description={`Room ${deleteRoom.number} · ${deleteRoom.name ?? deleteRoom.type} will be removed from all room lists and booking availability. Past stay records are retained. Live reservations and open tasks must be resolved first.`} cancelLabel="Cancel" label="Delete Room" onClose={() => setDeleteRoom(null)} onConfirm={() => act({ type: 'room.delete', payload: { id: deleteRoom.id, confirmed: true } }, 'Room deleted')} />}
    {statusRoom && <RoomStatusForm room={statusRoom} onClose={() => setStatusRoom(null)} />}
    {toggleRoom && <Confirm title={`${toggleRoom.active === false ? 'Activate' : 'Deactivate'} room ${toggleRoom.number}?`} description={toggleRoom.active === false ? 'The room will return to the active inventory. Readiness and maintenance checks still apply.' : 'This room will be removed from booking availability. Existing live reservations must be transferred or cancelled first.'} label={toggleRoom.active === false ? 'Activate room' : 'Deactivate room'} onClose={() => setToggleRoom(null)} onConfirm={() => act({ type: 'room.toggle', payload: { id: toggleRoom.id, active: toggleRoom.active === false } }, 'Room availability updated')} />}
    {resolveRoom && <Modal open title={`Resolve issue · Room ${resolveRoom.number}`} description="Confirm that the issue has been resolved and inspected. Request cleaning when needed." onClose={() => setResolveRoom(null)}><div className="dialog-body"><label className="property-checkbox"><input type="checkbox" checked={cleaningRequired} onChange={e => setCleaningRequired(e.target.checked)} />Cleaning required before the next guest</label></div><div className="dialog-footer"><Button variant="outline" onClick={() => setResolveRoom(null)}>Cancel</Button><Button onClick={() => { if (act({ type: 'room.resolve', payload: { id: resolveRoom.id, cleaningRequired } }, cleaningRequired ? 'Issue resolved. Housekeeping task created.' : 'Issue resolved. Room is available.')) setResolveRoom(null); }}>Confirm resolution</Button></div></Modal>}
    {taskRoom && <TaskForm roomId={taskRoom} onClose={() => setTaskRoom('')} />}
  </PageMotion>;
}
function RoomForm({ room, onClose }: { room?: Room; onClose: () => void }) {
  const { s, act } = useStore();
  const [v, setV] = useState<Record<string, any>>({ number: '', floor: '1', type: s.roomTypes?.[0] || 'Garden Deluxe', capacity: 2, bedType: 'King', beds: 1, rate: 5000, description: '', status: 'Available', ...room, images: room?.images ?? [], amenityIds: room?.amenityIds ?? [] });
  const [busy, setBusy] = useState(false);
  const [addingType, setAddingType] = useState(false);
  const [newType, setNewType] = useState('');
  
  const change = (key: string, value: any) => {
    if (key === 'type' && value === '+ Add New Room Type') {
      setAddingType(true);
      return;
    }
    setV(previous => ({ ...previous, [key]: value }));
  };

  const addType = () => {
    const t = newType.trim();
    if (t) {
      act({ type: 'property.addRoomType', payload: { type: t } }, '');
      setV(prev => ({ ...prev, type: t }));
    }
    setAddingType(false);
    setNewType('');
  };

  return <Modal open wide title={room ? `Edit room ${room.number}` : 'Add room'} description="Room details are shared with reservations, housekeeping, and Owner monitoring." onClose={onClose}><form onSubmit={e => { e.preventDefault(); if (!busy && act({ type: room ? 'room.update' : 'room.create', payload: v }, room ? 'Room updated' : 'Room added to the resort')) onClose(); }}><div className="dialog-body property-form"><Fields values={v} onChange={change} fields={[{ name: 'number', label: 'Room number', required: true }, { name: 'floor', label: 'Floor', required: true }, ...(!addingType ? [{ name: 'type', label: 'Room type', type: 'select', required: true, options: [...(s.roomTypes || []), '+ Add New Room Type'].map(value => ({ value, label: value })) }] : []), { name: 'capacity', label: 'Capacity', type: 'number', min: 1, max: 30, required: true }, { name: 'bedType', label: 'Bed type', type: 'select', required: true, options: ['Single', 'Twin', 'Queen', 'King', 'Bunk'].map(value => ({ value, label: value })) }, { name: 'beds', label: 'Number of beds', type: 'number', min: 1, max: 20, required: true }, { name: 'rate', label: 'Base price (₹ / night)', type: 'number', min: 1, max: 1000000, step: 1, required: true }, { name: 'description', label: 'Description', type: 'textarea', wide: true }]} />
  {addingType && (
    <div style={{ display: 'flex', gap: '8px', marginTop: '-12px', marginBottom: '16px' }}>
      <input autoFocus placeholder="New room type..." value={newType} onChange={e => setNewType(e.target.value)} style={{ flex: 1, padding: '8px', borderRadius: '6px', border: '1px solid var(--border)', background: 'var(--bg)', color: 'var(--text)' }} />
      <Button type="button" onClick={addType}>Add</Button>
      <Button type="button" variant="ghost" onClick={() => { setAddingType(false); setNewType(''); }}>Cancel</Button>
    </div>
  )}
  <h3>Room images</h3><PropertyMedia images={v.images} onChange={images => change('images', images)} onBusy={setBusy} />
  <h3>Amenities</h3><div className="property-check-grid">{s.amenities.filter(a => a.type === 'Room').map(a => <label className="property-checkbox" key={a.id}><input type="checkbox" checked={v.amenityIds.includes(a.id)} onChange={e => change('amenityIds', e.target.checked ? [...v.amenityIds, a.id] : v.amenityIds.filter((id: string) => id !== a.id))} /><span>{a.name}<small>{a.active && !a.maintenance ? a.category : 'Currently unavailable'}</small></span></label>)}{!s.amenities.some(a => a.type === 'Room') && <p className="muted">Add Room amenities in Amenities management to assign them here.</p>}</div></div><div className="dialog-footer"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{room ? 'Save room' : 'Add room'}<Check size={15} /></Button></div></form></Modal>;
}
function RoomStatusForm({ room, onClose }: { room: Room; onClose: () => void }) {
  const { s, act } = useStore();
  const [v, setV] = useState<Record<string, any>>({ status: room.status === 'Ready' ? 'Available' : room.status === 'Dirty' ? 'Cleaning' : room.status, notes: '', transferRoomId: '' });
  const stay = s.reservations.find(r => r.roomId === room.id && r.status === 'Checked in');
  return <Modal open title={`Change status · Room ${room.number}`} description="Reserved and Occupied follow the reservation lifecycle. Cleaning and maintenance create assigned work." onClose={onClose}><form onSubmit={e => { e.preventDefault(); if (act({ type: 'room.status', payload: { id: room.id, ...v } }, 'Room status and tasks updated')) onClose(); }}><div className="dialog-body"><Fields values={v} onChange={(key, value) => setV({ ...v, [key]: value })} fields={[{ name: 'status', label: 'New status', type: 'select', required: true, options: (stay ? ['Maintenance', 'Out of Service'] : ['Available', 'Cleaning', 'Maintenance', 'Out of Service']).map(value => ({ value, label: value })) }, ...(stay ? [{ name: 'transferRoomId', label: 'Transfer guest to room', type: 'select', required: true, options: s.rooms.filter(r => r.id !== room.id && r.status === 'Ready' && r.capacity >= stay.adults && available(s, r.id, today(), stay.checkOut)).map(r => ({ value: r.id, label: `${r.number} · ${r.type}` })) }] : []), { name: 'notes', label: 'Notes / issue description', type: 'textarea', wide: true }]} />{stay && <div className="info-box">The guest will be transferred before this room is blocked. Their original nightly rate is retained.</div>}</div><div className="dialog-footer"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit">Save status</Button></div></form></Modal>;
}
